// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSMv3gPtEW66CpTFYmaKY7lTXM_rwDaT8',
    appId: '1:687874838162:web:7d650459eb624ef291204b',
    messagingSenderId: '687874838162',
    projectId: 'pequesfcapp',
    authDomain: 'pequesfcapp.firebaseapp.com',
    storageBucket: 'pequesfcapp.firebasestorage.app',
    measurementId: 'G-V7JZ1QVMKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATtMCMT0zJ64nl1CSdxscls5ENoieyOn4',
    appId: '1:687874838162:android:4db6ff4f8705266c91204b',
    messagingSenderId: '687874838162',
    projectId: 'pequesfcapp',
    storageBucket: 'pequesfcapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ_4ZZmjuRzQJdBmXXK6aFQjnhvOwvr34',
    appId: '1:687874838162:ios:d3f525407d723ce191204b',
    messagingSenderId: '687874838162',
    projectId: 'pequesfcapp',
    storageBucket: 'pequesfcapp.firebasestorage.app',
    iosBundleId: 'com.example.pequesfcapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ_4ZZmjuRzQJdBmXXK6aFQjnhvOwvr34',
    appId: '1:687874838162:ios:d3f525407d723ce191204b',
    messagingSenderId: '687874838162',
    projectId: 'pequesfcapp',
    storageBucket: 'pequesfcapp.firebasestorage.app',
    iosBundleId: 'com.example.pequesfcapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSMv3gPtEW66CpTFYmaKY7lTXM_rwDaT8',
    appId: '1:687874838162:web:a598b2cf2a88449591204b',
    messagingSenderId: '687874838162',
    projectId: 'pequesfcapp',
    authDomain: 'pequesfcapp.firebaseapp.com',
    storageBucket: 'pequesfcapp.firebasestorage.app',
    measurementId: 'G-DLTCYGWYTW',
  );
}
