name: PequesFCApp
description: A payment registration and control application for the football school "PEQUES F.C."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter 
  flutter_riverpod: ^2.5.1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_form_builder: ^10.2.0
  uuid: ^4.5.1
  image_picker: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.10.4
  printing: ^5.14.2
  google_fonts: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/jugador.png
    - assets/peques.png
    - assets/rival.png
    - assets/profesor.png
    - assets/apoderado.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/peques.png"

