name: PequesFCApp
description: A payment registration and control application for the football school "PEQUES F.C."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_form_builder: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/peques.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/peques.png"

